version: '3'

services:
  reprepro:
    image: reprepro-docker
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "22:22"
    volumes:
      - ./config:/config:ro
      - ./data/:/data
